language: node_js
node_js:
- node
sudo: required
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - representativo.org
  - 45.55.142.185 # representativo.org
  hosts:
    representativo
  sauce_connect:
    username: andregs
  jwt:
    secure: YmYvM9NAMq/JRHx3qrlZc8Pf6W5Nu82gQZiT2QGZgPGQMwAGKU8CP/65bjP1n0PpKRsX1uV7sZlGFW1+GlqZKdPM5JRtYyR166fuOqMKVqKofY9tb7ZfenhUe+CSJBeH84e4TKdIV8luivBXWX+4WwH4T0N0+FwoWSujW92Z93eKyISKoHv6DKg2goo0wbeejNH/FF9sx4CqNTKmJj4rc6gXj5GscJvxEmBu68lUmwxqa0VpkqmO5q52YAek7KnSa0vrT2RGADEx5oHdpVrHX101yyVq9H0YSb4Zym6DOOh+/3KfOBs1h+0yor2uSx9JCvKjpsPaYlQNNFpoNmxopSDIhsl5fWr0ygRKX0M7TwzGQubaZrW4PYcdGrhgdJo5NCpmOSaBlufe08st5JdZNbDQe6CldscdV5lkuC8D6PvORpFGXmk0HPS5MhPwhsuNulvS2xqmXHynLMZIT4TNuPrKio0c2Mh3lJwQ6BEipp2FoBjYVDXu/np6GX6Dt7Moht8HkAqtwuBJVgy8MhTSgGVKLblzaRFQmZOP8ayi3KKfbYTzv4eFiXzATNDXMOGNNttHiExYZE+QpYh0nahcWgNud2WmfuPeR4ijf8aqEMtH4p79PNT+22RJHSlhqg9WmS+dj2NORt2TIoxm3Gc/qXlaLRj4fiX1G/EQsQpTDP4=
before_install:
- "./script/before-install.sh"
script:
- npm run -s db:create
- npm run -s build-prod
- npm test
- nohup bash -c "npm start &"
- sleep 7
- cat nohup.out
- npm run e2e
after_success: npm run coverage
deploy:
  skip_cleanup: true
  provider: script
  script: script/deploy.sh
  on:
    branch: master
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1a4bab705b8648486f8c
    on_success: change
    on_start: never
env:
  global:
  - secure: U5x5wNe0nWFB3/1s7gn6u03+FvA5zi0MjgLWlvtzQgnd/qPNCH4lXf1Y/oSsYFuqkQ1m3MraqrIwln2FEHTqRnNnUmAZ5pgT16C1obwBSLvbK0gUIoc59gK4AMxcRRzKfc+rGGAoIYDKndZrDmNorvxl5xTMYF1/wXEbN+GKLPUVcAvfmqWIHpEBL9k51hUt8bPBBZCaoenWuUtlTBN9C1zyvkygSxjicG0oaRQM1uRFS83n+0WVMDWfWBjiPxE6aM0oPfFg2P++pWe6Wi5trrg7O6qfckY62c1MRm/Pt6zxiVh4Yv98dMdLJRXM2DU29W4SenOiIySLyNPXKR/l9dNtl+YP2yyPVc+QW749d+ybVZP96oxat+Zm1PzAtDFdvKAy/vJrH9vWcPWKQJ4Q0cjD3IgDz+i4IBqZct9NcHmy9K0PFV908E9N/xqDK+VOEDZ/oTIbypIZJrCL2PJMIzzMeg7zBBD8vRw4pAhnecGdLNb4YnQHwcDIovTPKGZhJPd5oDoTIXjd/Wk+uivbef1WYbxQBqkIZyQPpS5LbZFIuXRIKeYqFjvqzpPJksR/0ae9oT6+iRStnSYLEbUkoFH+OfZleg87MRy8Uo1xrUE4/wIpHALUX6zooxYOt6Zq6+Nuzw3VDJFWPF+pHRWFeiYRrC/CkFVPsyY3J8s7ifo=
  - TS_NODE_COMPILER_OPTIONS='{"target":"es6"}'
