language: node_js
node_js:
- node
sudo: required
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: representativo.org
before_install:
- "./script/before-install.sh"
before_script:
- "./script/before-script.sh"
script:
- npm run build-prod
after_success:
- "./script/deploy.sh"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1a4bab705b8648486f8c
    on_success: change
    on_start: never
env:
  global:
  - secure: lROO3Ny/GhaesQaxZEfqE0bnD1hyHPGxCP/N7ykp9GHh+pczjwTNjz25jk+WUSBiiuCwmatrV3wyLnjXPtPikRON428KtEfD5Fno3YrtgvDZiArQcBMhkF/a6gK0pIHRBzSV1d8zrlPvGjSAvxcS5Cp0l9q5chnlMHl++SKMJFIeWPkbBYa2bFZw2lA30lBoV7x53rKunVX6tNQPW7jdWvB4UQAfq6gXxh4gajiAO2o2EpYvXsbV4mTIx3BhJvcclQ5tciD+q6YgECwlQu432CHuxo0LbyNtgkA60ALFhdED3VS3MrsmX8PkVKHFOoCZCCs9Jgp8aUAc8esUH13cyWKiEAFBeh7uzJOmI0EUQzFWntDoY+Qq1y6VA5I1R8D5kBqKABfmYTQjL2l8P3OKikvdfdBZs6Y+wr8O7bvBwC8H5T8Dpykte6kN5ntOKOKIfubW+K8XJfLPGFuByvvZ31t0ahE4P8gfckw6JOboiWqaM1BzuFbl7ZUOtP3ObdgV6kyOiBAGRjPSXwO+FCcV8Fun6fRtMI+HTpFP+vXo5A+hgVG/J3yHyqT5A1PuMnQQvTRW3sqtkj2JrE+7ugB7ikThIYMZKttdo5ClTJnaOFclBCsFyCsBG1AKYNoLRcSS2UBQdBS1HWshzdLuNnEcnSo4ekReBE6xzkqsm+/eb9g=
